# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{administer}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.rubygems_version = %q{1.3.7}
  
  s.authors = ["Piotr Jakubowski", "Marcin Bali\u0144ski"]
  s.date = %q{2010-12-06}
  s.email = ["piotrj@gmail.com", "balinski@gmail.com"]
  s.homepage = %q{http://github.com/piotrj/administer}
  s.summary = %q{Automatic admin interface generation}
  s.description = %q{}
  
  s.files = Dir.glob("{app,config,lib}/**/*")
  s.test_files = Dir.glob("spec/**/*")
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.require_paths = ["lib"]
  
  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 3.0.18"])
    else
      s.add_dependency(%q<haml>, [">= 3.0.18"])
    end
  else
    s.add_dependency(%q<haml>, [">= 3.0.18"])
  end
end

